
package pa.combatedesumos.Cliente.Vista;

import pa.combatedesumos.Cliente.Control.ControlVista;

/**
 *
 * @author VALEN
 */
public class PanelEspera extends javax.swing.JPanel {
    private ControlVista controlVista;
    /**
     * Creates new form PanelPrincipal
     */
    public PanelEspera(ControlVista controlVista) {
        this.controlVista = controlVista;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new PanelFondo("Imgs/Cliente/EsperandoAIniciarCombate.png");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1Salir.setBackground(new java.awt.Color(102, 0, 0));
        jButton1Salir.setFont(new java.awt.Font("Colonna MT", 1, 14)); // NOI18N
        jButton1Salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton1Salir.setText("Salir");
        jButton1Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SalirActionPerformed(evt);
            }
        });
        add(jButton1Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\CombateDeSumos\\Imgs\\EsperandoAIniciarCombate.png")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1SalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
