
package pa.combatedesumos.Cliente.Vista;

import pa.combatedesumos.Cliente.Control.ControlVista;

/**
 *
 * @author VALEN
 */
public class PanelRegistro extends javax.swing.JPanel {

    private ControlVista controlVista;
    /**
     * Creates new form PanelPrincipal
     */
    public PanelRegistro(ControlVista controlVista) {
        this.controlVista = controlVista;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1Nombre = new javax.swing.JTextField();
        jTextField2Peso = new javax.swing.JTextField();
        jButton2EnviarDatos = new javax.swing.JButton();
        jButton1SeleccionarTecnicas = new javax.swing.JButton();
        jPanel1 = new PanelFondo("Imgs/Cliente/Registrarse.png");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1Nombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1Nombre.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jTextField1Nombre.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1NombreActionPerformed(evt);
            }
        });
        add(jTextField1Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 210, 40));

        jTextField2Peso.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2Peso.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jTextField2Peso.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2PesoActionPerformed(evt);
            }
        });
        add(jTextField2Peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 195, 210, 40));

        jButton2EnviarDatos.setBackground(new java.awt.Color(153, 51, 0));
        jButton2EnviarDatos.setFont(new java.awt.Font("Colonna MT", 1, 32)); // NOI18N
        jButton2EnviarDatos.setForeground(new java.awt.Color(255, 255, 255));
        jButton2EnviarDatos.setText("Enviar Datos");
        jButton2EnviarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2EnviarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2EnviarDatosActionPerformed(evt);
            }
        });
        add(jButton2EnviarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 315, 220, 45));

        jButton1SeleccionarTecnicas.setBackground(new java.awt.Color(153, 51, 0));
        jButton1SeleccionarTecnicas.setFont(new java.awt.Font("Colonna MT", 1, 33)); // NOI18N
        jButton1SeleccionarTecnicas.setForeground(new java.awt.Color(255, 255, 255));
        jButton1SeleccionarTecnicas.setText("Seleccionar Técnicas");
        jButton1SeleccionarTecnicas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1SeleccionarTecnicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SeleccionarTecnicasActionPerformed(evt);
            }
        });
        add(jButton1SeleccionarTecnicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 360, 45));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SeleccionarTecnicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SeleccionarTecnicasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1SeleccionarTecnicasActionPerformed

    private void jButton2EnviarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2EnviarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2EnviarDatosActionPerformed

    private void jTextField1NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1NombreActionPerformed

    private void jTextField2PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2PesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2PesoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1SeleccionarTecnicas;
    public javax.swing.JButton jButton2EnviarDatos;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField1Nombre;
    public javax.swing.JTextField jTextField2Peso;
    // End of variables declaration//GEN-END:variables
}
