
package pa.combatedesumos.Cliente.Vista;

import pa.combatedesumos.Cliente.Control.ControlVista;

/**
 *
 * @author VALEN
 */
public class PanelPrincipal extends javax.swing.JPanel {
    private ControlVista controlVista;
    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal(ControlVista controlVista) {
        this.controlVista = controlVista;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2Salir = new javax.swing.JButton();
        jButton1IrRegistarse = new javax.swing.JButton();
        jPanel1 = new PanelFondo("Imgs/Cliente/PrincipalCliente.png");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2Salir.setBackground(new java.awt.Color(0, 0, 102));
        jButton2Salir.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jButton2Salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton2Salir.setText("Salir");
        jButton2Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2SalirActionPerformed(evt);
            }
        });
        add(jButton2Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 220, 50));

        jButton1IrRegistarse.setBackground(new java.awt.Color(0, 0, 102));
        jButton1IrRegistarse.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jButton1IrRegistarse.setForeground(new java.awt.Color(255, 255, 255));
        jButton1IrRegistarse.setText("Registrarse");
        jButton1IrRegistarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1IrRegistarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1IrRegistarseActionPerformed(evt);
            }
        });
        add(jButton1IrRegistarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 265, 220, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1IrRegistarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1IrRegistarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1IrRegistarseActionPerformed

    private void jButton2SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2SalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1IrRegistarse;
    public javax.swing.JButton jButton2Salir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
