
package pa.combatedesumos.Cliente.Vista;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import pa.combatedesumos.Cliente.Control.CControlVista;

/**
 * Panel que muestra las categorias y tecnicas kimarite con checkboxes para que
 * el luchador seleccione en cuales es experto.
 * El ComboBox de categorias se agrega por codigo ya que el wizard no lo incluia.
 *
 * @author VALEN
 */
public class PanelTecnicas extends javax.swing.JPanel {
 
    private CControlVista controlVista;
    private JCheckBox[] checkboxes;
    private ArrayList<String> tecnicasAcumuladas;
    
 
    /**
     * Constructor de PanelTecnicas.
     *
     * @param controlVista controlador de vista del cliente
     */
    public PanelTecnicas(CControlVista controlVista) {
        this.controlVista = controlVista; 
        initComponents();
        tecnicasAcumuladas = new ArrayList<>();
        initComboCategoriasExtra();
    }
 
    /**
     * Agrega el ComboBox de categorias encima del panel de checkboxes.
     * Se hace aqui en codigo porque el wizard no lo incluia.
     * Coordenadas: justo arriba de jPanel2ComboBoxes que esta en y=130.
     */
    private void initComboCategoriasExtra() {

    javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(jPanel2ComboBoxes);
    scroll.setOpaque(false);
    scroll.getViewport().setOpaque(false);
    scroll.setBorder(null);
    scroll.setHorizontalScrollBarPolicy(
        javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    scroll.setVerticalScrollBarPolicy(
        javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

    remove(jPanel2ComboBoxes);
    add(scroll,
        new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 280, 190));

    // ✅ CRÍTICO: mover al frente para quedar encima de jLabel1
    scroll.getParent(); // asegura que está en el contenedor
    setComponentZOrder(scroll, 0);         // 0 = más al frente
    setComponentZOrder(comboCategorias, 0); // el combo también al frente
}

    /**
     * Retorna el panel donde se agregan los checkboxes dinamicamente.
     */
    public javax.swing.JPanel getPanelCheckboxes() {
        return jPanel2ComboBoxes;
    }
 
    /**
     * Retorna el combobox de categorias.
     */
    public JComboBox<String> getComboCategorias() {
        return comboCategorias;
    }
 
    /**
     * Retorna los checkboxes de la categoria actualmente visible.
     */
    public JCheckBox[] getCheckboxes() {
        return checkboxes;
    }
 
    /**
     * Establece los checkboxes de la categoria actualmente visible.
     */
    public void setCheckboxes(JCheckBox[] checkboxes) {
        this.checkboxes = checkboxes;
    }
 
    /**
     * Retorna la lista acumulada de tecnicas seleccionadas de todas las categorias.
     */
    public ArrayList<String> getTecnicasAcumuladas() {
        return tecnicasAcumuladas;
    }
 
    /**
     * Retorna la categoria actualmente seleccionada en el combobox.
     */
    public String getCategoriaSeleccionada() {
        return (String) comboCategorias.getSelectedItem();
    }
 
    /**
     * Retorna todas las tecnicas seleccionadas acumuladas como arreglo.
     */
    public String[] getTecnicasSeleccionadas() {
        return tecnicasAcumuladas.toArray(new String[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1ConfirmarSeleccion = new javax.swing.JButton();
        comboCategorias = new javax.swing.JComboBox<>();
        jPanel2ComboBoxes = new javax.swing.JPanel();
        jPanel1 = new PanelFondo("Imgs/Cliente/SeleccionarTecnicas.png");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1ConfirmarSeleccion.setBackground(new java.awt.Color(102, 0, 0));
        jButton1ConfirmarSeleccion.setFont(new java.awt.Font("Colonna MT", 1, 20)); // NOI18N
        jButton1ConfirmarSeleccion.setForeground(new java.awt.Color(255, 255, 255));
        jButton1ConfirmarSeleccion.setText("Confirmar Selección");
        jButton1ConfirmarSeleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1ConfirmarSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConfirmarSeleccionActionPerformed(evt);
            }
        });
        add(jButton1ConfirmarSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 240, 40));

        comboCategorias.setBackground(new java.awt.Color(161, 19, 54));
        comboCategorias.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        comboCategorias.setForeground(new java.awt.Color(255, 255, 255));
        comboCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 280, -1));

        jPanel2ComboBoxes.setBackground(new java.awt.Color(112, 71, 71));

        javax.swing.GroupLayout jPanel2ComboBoxesLayout = new javax.swing.GroupLayout(jPanel2ComboBoxes);
        jPanel2ComboBoxes.setLayout(jPanel2ComboBoxesLayout);
        jPanel2ComboBoxesLayout.setHorizontalGroup(
            jPanel2ComboBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel2ComboBoxesLayout.setVerticalGroup(
            jPanel2ComboBoxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        add(jPanel2ComboBoxes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 280, 190));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ConfirmarSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConfirmarSeleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ConfirmarSeleccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> comboCategorias;
    public javax.swing.JButton jButton1ConfirmarSeleccion;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2ComboBoxes;
    // End of variables declaration//GEN-END:variables
}
