
package pa.combatedesumos.Servidor.Vista;

import java.awt.Image;
import java.awt.image.ImageObserver;
import java.io.File;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import pa.combatedesumos.Servidor.Control.SrvControlVista;

/**
 *
 * @author VALEN
 */
public class PanelDojo extends javax.swing.JPanel {
    private SrvControlVista controlVista;
    /**
     * Creates new form PanelPrincipal
     */
    public PanelDojo(SrvControlVista controlVista) {
        this.controlVista = controlVista;
        initComponents();
    }
    
    public boolean cargarGifAleatorio() {

    // 1. Buscar los GIFs en la carpeta IMGS/GIFS
    URL carpetaUrl = getClass().getResource("/Imgs/Gifs/Tecnicas");

    File carpetaGifs = new File(carpetaUrl.getPath());
    File[] archivos = carpetaGifs.listFiles(
        (dir, nombre) -> nombre.toLowerCase().endsWith(".gif")
    );

    // 2. Seleccionar uno al azar
    int indice = (int) (Math.random() * archivos.length);
    File gifElegido = archivos[indice];

    // 3. Escalar al tamaño del panel
    ImageIcon gifOriginal = new ImageIcon(gifElegido.getAbsolutePath());

    int ancho = 258;
    int alto  = 230;

    Image gifEscalado = gifOriginal.getImage()
            .getScaledInstance(ancho, alto, Image.SCALE_DEFAULT);

    ImageIcon gifIconFinal = new ImageIcon(gifEscalado);

    // 4. Asignar al label
    Gifs.setIcon(gifIconFinal);
    Gifs.setHorizontalAlignment(SwingConstants.CENTER);
    Gifs.setVerticalAlignment(SwingConstants.CENTER);

    // 5. Detectar cuando el GIF termina (último frame)
    gifIconFinal.setImageObserver(new ImageObserver() {
        private int ultimoFrame = -1;

        @Override
        public boolean imageUpdate(Image img, int infoflags,
                                   int x, int y, int width, int height) {

            if ((infoflags & ImageObserver.ALLBITS) != 0) {
                // GIF terminó de reproducirse
                //SwingUtilities.invokeLater(() -> alTerminarGif());
                return false; // dejar de observar
            }
            return true; // seguir observando
        }
    });

    return true; // GIF cargado exitosamente
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jugador1 = new javax.swing.JTextField();
        Jugador2 = new javax.swing.JTextField();
        Gifs = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jugador1.setBackground(new java.awt.Color(153, 102, 0));
        Jugador1.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        Jugador1.setForeground(new java.awt.Color(255, 255, 255));
        Jugador1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Jugador1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jugador1ActionPerformed(evt);
            }
        });
        add(Jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 230, 70));

        Jugador2.setBackground(new java.awt.Color(153, 102, 0));
        Jugador2.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        Jugador2.setForeground(new java.awt.Color(255, 255, 255));
        Jugador2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Jugador2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jugador2ActionPerformed(evt);
            }
        });
        add(Jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 230, 70));
        add(Gifs, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 230, 410, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void Jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jugador1ActionPerformed

    private void Jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jugador2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Gifs;
    public javax.swing.JTextField Jugador1;
    public javax.swing.JTextField Jugador2;
    // End of variables declaration//GEN-END:variables
}
