
package pa.combatedesumos.Servidor.Vista;

import java.awt.Image;
import java.awt.image.ImageObserver;
import java.io.File;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import pa.combatedesumos.Servidor.Control.SrvControlVista;

/**
 * Panel que muestra el dohyō y sincroniza los GIFs de los kimarites.
 * 
 * @author VALEN
 */
public class PanelDojo extends javax.swing.JPanel implements IGifSincronizado {
    
    private SrvControlVista controlVista;
    private JLabel gifActual;
    private volatile boolean gifTerminado = false;
    private volatile boolean gifActivo = false;
    
    public PanelDojo(SrvControlVista controlVista) {
        this.controlVista = controlVista;
        initComponents();
    }
    /**
     * Reproduce un GIF y espera a que termine completamente
     * @param rutaGif ruta del GIF
     * @param alTerminar callback cuando termine
     */
    @Override
    public void reproducirGifYEsperar(String rutaGif, Runnable alTerminar) {
        SwingUtilities.invokeLater(() -> {
            try {
                gifTerminado = false;
                gifActivo = true;
                
                // Cargar GIF
                URL recursoUrl = getClass().getResource(rutaGif);
                if (recursoUrl == null) {
                    gifActivo = false;
                    gifTerminado = true;
                    if (alTerminar != null) alTerminar.run();
                    return;
                }
                
                ImageIcon gifIcon = new ImageIcon(recursoUrl);
                
                // Detectar fin del GIF
                gifIcon.setImageObserver(new ImageObserver() {
                    private boolean seEjecuto = false;
                    
                    @Override
                    public boolean imageUpdate(Image img, int infoflags, 
                            int x, int y, int width, int height) {
                        if ((infoflags & ImageObserver.FRAMEBITS) != 0) {
                            seEjecuto = true;
                        }
                        if ((infoflags & ImageObserver.ALLBITS) != 0 && seEjecuto) {
                            // GIF terminó
                            gifTerminado = true;
                            gifActivo = false;
                            if (alTerminar != null) {
                                SwingUtilities.invokeLater(alTerminar);
                            }
                            return false;
                        }
                        return true;
                    }
                });
                
                // Mostrar GIF
                Gifs.setIcon(gifIcon);
                Gifs.setHorizontalAlignment(SwingConstants.CENTER);
                
            } catch (Exception e) {
                gifActivo = false;
                gifTerminado = true;
                if (alTerminar != null) alTerminar.run();
            }
        });
    }

    /**
     * Detiene el GIF actual
     */
    @Override
    public void detenerGif() {
        SwingUtilities.invokeLater(() -> {
            gifActivo = false;
            gifTerminado = true;
            if (Gifs != null) {
                Gifs.setIcon(null);
            }
        });
    }

    /**
     * Actualiza los nombres de los combatientes
     */
    public void actualizarCombatientes(String luchador1, String luchador2) {
        SwingUtilities.invokeLater(() -> {
            Jugador1.setText(luchador1);
            Jugador2.setText(luchador2);
        });
    }

    /**
     * Actualiza el mensaje del combate
     */
    public void actualizarMensaje(String mensaje) {
        SwingUtilities.invokeLater(() -> {
            // Implementar según el panel
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jugador1 = new javax.swing.JTextField();
        Jugador2 = new javax.swing.JTextField();
        Gifs = new javax.swing.JLabel();
        jPanel1 = new PanelFondo("Imgs/Servidor/Combate.png");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jugador1.setBackground(new java.awt.Color(153, 102, 0));
        Jugador1.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        Jugador1.setForeground(new java.awt.Color(255, 255, 255));
        Jugador1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Jugador1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jugador1ActionPerformed(evt);
            }
        });
        add(Jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 230, 70));

        Jugador2.setBackground(new java.awt.Color(153, 102, 0));
        Jugador2.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        Jugador2.setForeground(new java.awt.Color(255, 255, 255));
        Jugador2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Jugador2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Jugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jugador2ActionPerformed(evt);
            }
        });
        add(Jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 230, 70));
        add(Gifs, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 230, 410, 270));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void Jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jugador1ActionPerformed

    private void Jugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jugador2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Gifs;
    public javax.swing.JTextField Jugador1;
    public javax.swing.JTextField Jugador2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
