
package pa.combatedesumos.Servidor.Vista;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.SwingUtilities;
import pa.combatedesumos.Servidor.Control.SrvControlVista;

/**
 *
 * @author VALEN
 */
public class PanelInscritos extends javax.swing.JPanel {

    private SrvControlVista controlVista;
    private DefaultListModel<String> modeloLuchadores;
    private JList<String> listaSumos;
    /**
     * Creates new form PanelPrincipal
     */
    public PanelInscritos(SrvControlVista controlVista) {
        this.controlVista = controlVista;
        initComponents();
        configurarLista();
    }
    
    /**
     * Configura el modelo y la lista de luchadores
     */
    private void configurarLista() {
        modeloLuchadores = new DefaultListModel<>();
        listaSumos = new JList<>(modeloLuchadores);
        listaSumos.setFont(new java.awt.Font("Constantia", 0, 18));
        listaSumos.setBackground(new java.awt.Color(240, 240, 240));
        listaSumos.setForeground(new java.awt.Color(50, 50, 50));
        SumosRegistrados.setViewportView(listaSumos);
    }

    /**
     * Agrega un luchador a la lista de inscritos
     * @param nombreLuchador nombre del luchador a agregar
     */
    public void agregarLuchador(String nombreLuchador) {
        SwingUtilities.invokeLater(() -> {
            modeloLuchadores.addElement(nombreLuchador);
            listaSumos.updateUI();
        });
    }

    /**
     * Limpia todos los luchadores de la lista
     */
    public void limpiarLista() {
        SwingUtilities.invokeLater(() -> {
            modeloLuchadores.clear();
            listaSumos.updateUI();
        });
    }

    /**
     * Obtiene la lista de luchadores registrados
     * @return DefaultListModel con los luchadores
     */
    public DefaultListModel<String> getModeloLuchadores() {
        return modeloLuchadores;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SumosRegistrados = new javax.swing.JScrollPane();
        jButton1IrAlCombate = new javax.swing.JButton();
        jPanel1 = new PanelFondo("Imgs/Servidor/PantallaPrincipal.png");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(SumosRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 340, 310));

        jButton1IrAlCombate.setBackground(new java.awt.Color(102, 0, 0));
        jButton1IrAlCombate.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        jButton1IrAlCombate.setForeground(new java.awt.Color(255, 255, 255));
        jButton1IrAlCombate.setText("¡Combatir!");
        add(jButton1IrAlCombate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 220, 60));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane SumosRegistrados;
    public javax.swing.JButton jButton1IrAlCombate;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
